### PR TITLE
Story2task1

### PR DESCRIPTION
**Pull request by DBaldwin8**
S2T1: Add the form to add entry, frontend only. Currently using textbox this may be changed as needed for T2.

### CODE REVIEW

**Review by vincedefreitas — COMMENTED** [review]
This looks good to me Darren. The only comment I have is that I think labels (as in label tags) could be added to the inputs for accessibility purposes. I know you don't need them visually because you've got table headings, but my understanding is a screen reader will literally just read 'input' for the input fields. I'm not 100% sure though so feel free to ignore this.. Otherwise there might be a way to add labels and hide the text somehow? Again not 100% sure on this, it's only a thought!

**Comment by DBaldwin8** [comment]
> (as in label tags) could be added to the inputs for accessibility purposes

Actioned, added, also added a hover to the submit add to table.

**Comment by DBaldwin8** [comment]
Requesting peer review again.

**Review by FredJRice — COMMENTED** [review]
Looks good to me

**Pull request merged**
